version: '3.8'

services:
  webapp:
    build: .
    container_name: sharesub_webapp
    ports:
      - "8081:80" # Zugriff z. B. über http://SERVER_IP:8081
    volumes:
      - ./dist:/app/sharesub_webapp/dist
    restart: unless-stopped