version: '3.8'

services:
  webapp:
    build: .
    container_name: sharesub_webapp
    ports:
      - "8081:80"
    networks:
      - wp_net  # <<< damit NGINX Proxy Manager dich sieht
    restart: unless-stopped

networks:
  wp_net:
    external: true  # <<< wichtig: das Netzwerk existiert bereits (z. B. von deinem WordPress-Stack)